trigger:
  - main

pool:
  name: aks-pipeline-agent

stages:
- stage: Kubernetes_BoM
  jobs:
  - job: Generate_BoM
    steps:

    - task: AzureCLI@2
      displayName: "Authenticate with AKS"
      inputs:
        azureSubscription: "64002c0f-699d-400d-93d2-a40ec1226bcd"
        scriptType: "bash"
        scriptLocation: "inlineScript"
        inlineScript: |
          echo "Logging into Azure..."
          az login --service-principal -u $(ARM_CLIENT_ID) -p $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)

          echo "Fetching AKS credentials..."
          az aks get-credentials --resource-group "myResourceGroup" --name "myAKSCluster" --overwrite-existing

          echo "Verifying Kubernetes connection..."
          kubectl cluster-info

    - script: |
        echo "Fetching Kubernetes Cluster Details..."
        kubectl get nodes --all-namespaces -o json > nodes.json
        kubectl get pods --all-namespaces -o json > pods.json
        kubectl get deployments --all-namespaces -o json > deployments.json
        kubectl get services --all-namespaces -o json > services.json
        kubectl get configmaps --all-namespaces -o json > configmaps.json
        kubectl get secrets --all-namespaces -o json > secrets.json
        kubectl get ingresses --all-namespaces -o json > ingresses.json
        kubectl get daemonsets --all-namespaces -o json > daemonsets.json
        kubectl get statefulsets --all-namespaces -o json > statefulsets.json

        echo "Fetching Container Images Used in the Cluster..."
        kubectl get pods --all-namespaces -o json | jq '[.items[] | {namespace: .metadata.namespace, pod: .metadata.name, containers: [.spec.containers[].image]}]' > container_images.json

        echo "Combining BoM..."
        jq -s '{nodes: .[0], pods: .[1], deployments: .[2], services: .[3], configmaps: .[4], secrets: .[5], ingresses: .[6], daemonsets: .[7], statefulsets: .[8], container_images: .[9]}' \
          nodes.json pods.json deployments.json services.json configmaps.json secrets.json ingresses.json daemonsets.json statefulsets.json container_images.json > k8s_bom.json

    - task: PublishBuildArtifacts@1
      displayName: "Publish Kubernetes BoM"
      inputs:
        pathToPublish: 'k8s_bom.json'
        artifactName: 'KubernetesBoM'
