trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  CLUSTER_NAME: 'your-cluster-name'
  RESOURCE_GROUP: 'your-resource-group'
  NAMESPACE: 'default'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- task: AzureCLI@2
  inputs:
    azureSubscription: 'your-azure-subscription'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az aks get-credentials --resource-group $(RESOURCE_GROUP) --name $(CLUSTER_NAME)

- task: Kubernetes@1
  inputs:
    command: 'get'
    arguments: 'all --all-namespaces -o json'
    outputFormat: 'json'
    outputFile: '$(Build.ArtifactStagingDirectory)/k8s-resources.json'

- script: |
    helm list --all-namespaces -o json > $(Build.ArtifactStagingDirectory)/helm-charts.json
  displayName: 'Export Helm Chart Information'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'k8s-bom'
    publishLocation: 'Container'